<!Doctype html>
<html>
    <head>
        <title>Term And Condition</title>
        <style>
            @font-face {
                font-family: 'Nexa';
                src: url("file:///android_res/font/nexaregular.otf");
            }
            body{
                font-family: 'Nexa';
            }
        </style>
    </head>
    <body>
        <p><H1>Syarat dan Ketentuan</H1></p>
        <p><span style="font-weight: 400;">Selamat datang di Relasi Bisnis Bersama</span></p>
        <p><span style="font-weight: 400;">Disarankan sebelum mengakses Applikasi ini lebih jauh, Anda terlebih dahulu membaca dan memahami syarat dan ketentuan yang berlaku. Syarat dan ketentuan berikut adalah ketentuan dalam pengunjungan Applikasi, isi dan/atau konten, layanan, serta fitur lainnya yang ada di dalam Situs. Dengan mengakses atau menggunakan Applikasi lainnya yang disediakan oleh atau dalam Applikasi, berarti Anda telah memahami dan menyetujui serta terikat dan tunduk dengan segala syarat dan ketentuan yang berlaku di Situs ini.</span></p>
        <ol>
            <li><strong> DEFINISI</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Setiap kata atau istilah berikut yang digunakan di dalam Syarat dan Ketentuan ini memiliki arti seperti berikut di bawah, kecuali jika kata atau istilah yang bersangkutan di dalam pemakaiannya dengan tegas menentukan lain</span></p>

        <p><span style="font-weight: 400;">1.1. &ldquo;</span><strong>Kami&rdquo;</strong><span style="font-weight: 400;">, berarti PT Mahakarya Cipta Internasional selaku pemilik dan pengelola aplikasi</span><span style="font-weight: 400;">&nbsp;</span><em><span style="font-weight: 400;">mobile</span></em><span style="font-weight: 400;">&nbsp;yang bernama Rekan Bisnis Bersama (RBB).</span></p>
        <p><span style="font-weight: 400;">1.2.&nbsp;&ldquo;</span><strong>Anda&rdquo;</strong><span style="font-weight: 400;">, berarti tiap orang yang mengakses Applikasi dan menggunakan layanan dan jasa yang disediakan oleh Kami.</span></p>
        <p><span style="font-weight: 400;">1.3.&nbsp;&ldquo;</span><strong>Layanan&rdquo;</strong><span style="font-weight: 400;">, berarti setiap dan keseluruhan jasa serta informasi yang ada pada Applikasi, termasuk namun tidak terbatas pada informasi yang disediakan, fitur dan layanan aplikasi, dukungan data, serta&nbsp;aplikasi&nbsp;</span><em><span style="font-weight: 400;">mobile</span></em><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;">yang Kami sediakan.</span></p>
        <p><span style="font-weight: 400;">1.4.&nbsp;&ldquo;</span><strong>Pengguna&rdquo;</strong><span style="font-weight: 400;">, berarti tiap orang yang mengakses dan menggunakan layanan dan jasa yang disediakan oleh Kami dan sudah menjadi Pengguna Terdaftar.</span></p>
        <p><span style="font-weight: 400;">1.5. &ldquo;</span><strong>Pengguna Terdaftar&rdquo;</strong><span style="font-weight: 400;">, berarti tiap orang yang mengakses dan menggunakan layanan dan jasa yang disediakan oleh Kami, serta telah melakukan registrasi dan memiliki akun pada Situs Kami.</span></p>
        <p><span style="font-weight: 400;">1.6.&nbsp;&ldquo;</span><strong>Informasi Pribadi&rdquo;,&nbsp;</strong><span style="font-weight: 400;">berarti tiap dan seluruh data pribadi yang diberikan oleh Pengguna di Situs Kami, termasuk namun tidak terbatas pada nama lengkap, jenis kelamin, alamat lokasi pengguna, kontak pengguna, serta dokumen dan data pendukung lainnya sebagaimana diminta pada ringkasan pendaftaran akun serta pada ringkasan aplikasi pengajuan.</span></p>
        <p><span style="font-weight: 400;">1.7. &ldquo;</span><strong>Konten&rdquo;</strong><span style="font-weight: 400;">, berarti teks, data, informasi, angka, gambar, grafik, foto, audio, video, nama pengguna, informasi, aplikasi, tautan, komentar, peringkat, desain, atau materi lainnya yang ditampilkan pada Situs.engajuan.</span></p>
        <p><span style="font-weight: 400;">1.8. &ldquo;</span><strong>Applikasi</strong><span style="font-weight: 400;">&rdquo;, berarti Relasi Bisnis Bersama.</span></p>
        <ol start="2">
            <li><strong> LAYANAN DAN/ATAU JASA</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Kami memberikan informasi mengenai kontak para pengguna rekan applikasi RBB secara legal dan atas persetujuan pihak pengguna Aplikasi RBB. Layanan ini memungkinkan Anda untuk dapat melihat, membaca serta menghubungi Rekan RBB lain sesuai informasi yang di berikan oleh rekan RBB tersebut.</span></p>
        <p><span style="font-weight: 400;">2.1. Informasi yang terdapat dalam Applikasi Kami ditampilkan sesuai keadaan kenyataan untuk tujuan informasi umum. Kami berusaha untuk selalu menyediakan dan menampilkan informasi yang terbaru dan akurat, namun Kami tidak menjamin bahwa segala informasi sesuai dengan ketepatan waktu atau relevansi dengan kebutuhan Anda.</span></p>
        <p><span style="font-weight: 400;">2.2. Diharapkan Anda tidak menganggap atau berasumsi bahwa Applikasi ini dapat dijadikan sebagai saran keuangan dan/atau finansial, atau rekomendasi atas produk serta layanan yang ditampilkan oleh rekan RBB. Informasi di Applikasi ini disediakan untuk membantu Anda dalam memilih produk atau layanan yang sesuai dengan kebutuhan Anda. Anda sepenuhnya bertanggung jawab atas keputusan terkait pemilihan produk dan layanan, atau dalam menandatangani kontrak berkaitan dengan sebuah produk atau layanan. Dengan memberikan Kami rincian tentang diri pribadi Anda, dianggap Anda mengajukan diri untuk mendapatkan suatu produk atau layanan tertentu dari para rekan RBB lainnya. Dan setiap keputusan yang anda buat menjadi tanggung jawab anda sepenuhnya.</span></p>
        <p><span style="font-weight: 400;">2.3. Layanan yang Kami berikan tidak bersifat memaksa atau mengikat, serta tidak mengharuskan Anda untuk mengikuti informasi yang tersedia. Tidak ada situasi atau keadaan apapun yang dapat membuat Kami dikenakan tanggung jawab atas kemungkinan kerugian yang Anda alami karena pengambilan keputusan yang dilakukan oleh Anda sendiri terkait tindakan atas informasi produk yang kami sampaikan di Applikasi</span></p>
        <p><span style="font-weight: 400;">2.4. Kami memiliki hak untuk kapan saja menampilkan, mengubah, menghapus, menghilangkan, atau menambahkan segala konten yang ditampilkan dalam Situs ini.</span></p>
        <ol start="3">
            <li><strong> PENGGUNAAN LAYANAN DAN JASA</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Dengan Anda melanjutkan penggunaan atau pengaksesan Applikasi ini, berarti Anda telah menyatakan serta menjamin kepada Kami bahwa :</span></p>
        <p><span style="font-weight: 400;">3.1. Anda hanya diperkenankan untuk mengakses dan/atau menggunakan Applikasi ini untuk keperluan pribadi dan non-komersil, yang berarti bahwa Applikasi ini hanya boleh diakses dan digunakan secara langsung oleh individu atau bisnis yang sedang mencari produk atau layanan untuk individu atau bisnis tersebut. Akses dan penggunaan Applikasi diluar dari keperluan pribadi atau non-komersil dilarang keras, dan melanggar Syarat dan Ketentuan ini.</span></p>
        <p><span style="font-weight: 400;">3.2. Anda tidak diperkenankan menggunakan Applikasi dalam hal sebagai berikut :</span></p>
        <ul>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Untuk menyakiti, menyiksa, mempermalukan, memfitnah, mencemarkan nama baik, mengancam, mengintimidasi atau mengganggu orang atau bisnis lain, atau apapun yang melanggar privasi atau yang Kami anggap cabul, menghina, penuh kebencian, tidak senonoh, tidak patut, tidak pantas, tidak dapat diterima, mendiskriminasikan atau merusak.</span></li>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Dalam cara yang melawan hukum, tindakan penipuan atau tindakan komersil.</span></li>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Melanggar atau menyalahi hak orang lain, termasuk tanpa kecuali : hak paten, merek dagang, hak cipta, rahasia dagang, publisitas, dan hak milik lainnya.</span></li>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Untuk membuat, memeriksa, memperbarui, mengubah atau memperbaiki database, rekaman atau direktori Anda ataupun orang lain.</span></li>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Mengubah atau mengatur ulang bagian apapun dalam Situs ini yang akan mengganggu atau menaruh beban berlebihan pada sistem komunikasi dan teknis kami.</span></li>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Mengunakan kode komputer otomatis, proses, program, robot, net crawler, spider, pemrosesan data, trawling atau kode komputer, proses, program atau sistem&nbsp;</span><em><span style="font-weight: 400;">screen scraping</span></em><span style="font-weight: 400;">&nbsp;alternatif.</span></li>
            <li style="font-weight: 400;"><span style="font-weight: 400;">Melanggar Syarat dan Ketentuan, atau petunjuk lainnya yang ada pada Situs.</span></li>
        </ul>
        <p><span style="font-weight: 400;">3.3. Kami tidak bertanggung jawab atas kehilangan akibat kegagalan mengakses Applikasi, dan metode penggunaan Applikasi yang diluar kendali Kami.</span></p>
        <p><span style="font-weight: 400;">3.4. Kami tidak bertanggung jawab atau dapat dipersalahkan atas kehilangan atau kerusakan yang diluar perkiraan saat Anda mengakses atau menggunakan Applikasi ini. Ini termasuk kehilangan penghematan yang diharapkan, kehilangan bisnis atau kesempatan bisnis, kehilangan pemasukan atau keuntungan, atau kehilangan atau kerusakan apapun yang Anda harus alami akibat penggunaan Appliakasi ini.</span></p>
        <ol start="4">
            <li><strong> HAK INTELEKTUAL PROPERTI</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Semua Hak Kekayaan Intelektual yang ada di dalam Applikasi ini adalah milik Kami. Tiap atau keseluruhan informasi dan materi dan konten, termasuk&nbsp;namun&nbsp;tidak terbatas pada tulisan, perangkat lunak, teks, data, grafik, gambar, audio, video, logo, ikon atau kode-kode html dan kode-kode lain yang ada di Situs ini dilarang dipublikasikan, dimodifikasi, disalin, digandakan atau diubah dengan cara apapun di luar area Situs ini tanpa izin dari Kami. Pelanggaran terhadap hak-hak Situs ini dapat ditindak sesuai dengan peraturan yang berlaku.</span></p>
        <p><span style="font-weight: 400;">Anda dapat menggunakan informasi atau isi dalam Situs hanya untuk penggunaan pribadi non-komersil. Kecuali ditentukan sebaliknya dan/atau diperbolehkan secara tegas oleh undang-undang hak cipta, maka Pengguna dilarang untuk menyalin, membagikan ulang, mentransmisi ulang,&nbsp;meretas,&nbsp;mempublikasi atau melakukan tindakan eksploitasi komersial dari pengunduhan yang dilakukan tanpa seizin&nbsp;Kami</span><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;">sebagai</span><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;">pemilik Hak Intelektual Properti tersebut. Dalam hal Pengguna telah mendapatkan izin yang diperlukan maka Pengguna dilarang melakukan perubahan atau penghapusan. Pengguna dengan ini menyatakan menerima dan mengetahui bahwa dengan mengunduh materi Hak Intelektual Properti bukan berarti mendapatkan hak kepemilikan atas pengunduhan materi Hak Intelektual Properti tersebut.</span></p>
        <ol start="5">
            <li><strong> KOMENTAR</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Jika Anda ingin memberikan komentar, masukan, ataupun sanggahan mengenai tiap atau keseluruhan konten dan informasi dalam Situs, Kami juga menyediakan sarana chat/messaging dan kontak email </span><em><span style="font-weight: 400;">customer service</span></em><span style="font-weight: 400;"> kami.&nbsp;</span></p>
        <p><span style="font-weight: 400;">Anda diperbolehkan untuk memberi komentar, dan setuju bahwa jika diperlukan, akan Kami pergunakan untuk kepentingan informasi dan ditampilkan pada Applikasi Kami. Dan harap diperhatikan bahwa komentar, masukan, atau sanggahan yang Anda berikan tidak boleh bertentangan dengan Syarat dan Ketentuan ini, terutama seperti tercantum dalam poin 3.2.</span></p>
        <p><strong>6 PENGAJUAN</strong></p>
        <p><span style="font-weight: 400;">6.1. Anda bisa mengajukan diri untuk mendapatkan berbagai produk dan layanan seperti yang ditampilkan di Situs ini. Anda sepenuhnya bertanggung jawab atas pilihan produk atau layanan, dan Kami tidak bertanggung jawab atau dapat dipersalahkan atas kehilangan atau kerusakan yang mungkin Anda derita akibat produk atau layanan yang Anda dapatkan saat menggunakan Applikasi ini, atau atas tindakan, penghapusan atau kesalahan Pihak rekan RBB yang disebut di produk atau layanan itu.</span></p>
        <p><span style="font-weight: 400;">6.2. Diingatkan kembali bahwa data dan deskripsi produk dan jasa pada Applikasi ini mungkin tidak mewakili seluruh deskripsi dari semua pilihan dan persyaratan produk dan layanan tersebut. Anda perlu berhati-hati dan cermat untuk melihat semua pilihan dan syarat dan kondisi dari setiap produk atau jasa sebelum melakukan pengajuan.</span></p>
        <p><span style="font-weight: 400;">6.3. Jika Anda mengajukan permohonan dan mendapatkan produk atau layanan, Anda akan masuk ke dalam kontak dengan Pihak rekan RBB lainnya sebagai penyedia produk atau layanan, yang memiliki syarat dan ketentuan sendiri. Anda bertanggung jawab untuk memastikan bahwa Anda setuju dengan syarat dan kondisi sebelum memasuki kontrak untuk mendapatkan produk atau layanan dimaksud. Kami tidak bertanggung jawab atau disalahkan atas segala kerugian atau kerusakan yang mungkin Anda derita akibat syarat dan ketentuan yang berlaku di setiap kontrak antara Anda dengan Pihak rekan RBB lainnya, termasuk yang berhubungan tindakan, kelalaian atau kesalahan dari Pihak rekan RBB tersebut.</span></p>
        <p><span style="font-weight: 400;">6.4. Anda memberikan izin pada Kami untuk memproses data-data Anda kepada rekan RBB lainnya, serta memberi kuasa kepada rekan RBB lainnya untuk memeriksa semua informasi yang diberikan dengan cara bagaimanapun, menghubungi Anda untuk pemasaran dari produk maupun layanan yang disediakan oleh rekan RBB lainnya pada Applikasi, termasuk namun tidak terbatas untuk keperluan Sistem&nbsp;Layanan</span><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;">Informasi</span><span style="font-weight: 400;">&nbsp;</span><span style="font-weight: 400;">Keuangan (SLIK) OJK, biro kredit dan/atau sejenisnya.</span></p>
        <p><span style="font-weight: 400;">6.5. Anda memberikan izin pada Kami untuk memproses data Anda untuk meningkatkan layanan Kami dalam bentuk apapun, termasuk tapi tidak terbatas untuk keperluan pemasaran dan peningkatan layanan Kami.</span></p>
        <ol start="7">
            <li><strong> TAUTAN LAINNYA</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Situs Kami mungkin menyediakan beberapa tautan tertentu yang merujuk atau mengarahkan Anda ke laman rekan RBB lainnya, juga termasuk di dalamnya tautan yang tersedia pada halaman hasil pencarian produk tertentu. Anda mengetahui, memahami, serta menyetujui bahwa Kami tidak bertanggung jawab atas konten dan/atau materi lainnya yang terdapat dalam tautan milik rekan RBB tersebut. Anda bertanggung jawab atas resiko ketika mengakses dan menggunakan tautan milik rekan RBB lainnya tersebut. Dan disarankan Anda juga dapat membaca serta memahami isi dari Syarat dan Ketentuan yang berlaku di tautan milik rekan RBB lainnya tersebut.</span></p>
        <ol start="8">
            <li><strong> ATURAN KEANGGOTAAN</strong></li>
        </ol>
        <p><span style="font-weight: 400;">Selain menampilkan informasi produk layanan penambahan kontak, Kami juga menyediakan keanggotaan bagi Anda selaku Pengguna. Anda dapat memeriksa riwayat keuangan bonus Anda.</span></p>
        <p><span style="font-weight: 400;">8.1. Sebelum menjadi anggota (atau disebut dengan Pengguna Terdaftar), Anda diwajibkan membuat akun untuk diri Anda. Proses pembuatan akun dapat dilakukan secara online melalui Applikasi</span></p>
        <p><span style="font-weight: 400;">8.2.&nbsp;</span><span style="font-weight: 400;">Sebelum menjadi Pengguna Terdaftar, Anda diwajibkan membaca, memahami, dan mematuhi Syarat dan Ketentuan serta Kebijakan Privasi yang berlaku di Applikasi.</span></p>
        <p><span style="font-weight: 400;">8.3.&nbsp;Anda diharuskan memberi data Informasi Pribadi yang sebenarnya dan tidak memberikan informasi menyimpang dan/atau informasi yang tidak relevan dalam melakukan proses registrasi menjadi Pengguna Terdaftar. Selain itu Anda juga diharuskan memberi kontak detail yang benar dan valid.</span></p>
        <p><span style="font-weight: 400;">8.4.&nbsp;Kami berhak untuk tidak memproses registrasi Pengguna yang tidak memenuhi persyaratan ataupun tidak memberikan informasi yang benar dan valid, dan Kami berhak juga mengeluarkan Pengguna Terdaftar dari keanggotaan jika di kemudian hari ditemukan hal-hal yang melanggar ketentuan dari Kami.</span></p>
        <p><span style="font-weight: 400;">8.5.&nbsp;Pengguna yang telah sukses melakukan proses registrasi, dan menjadi Pengguna Terdaftar, dapat melakukan akses keanggotaan kapan pun melalui aplikasi&nbsp;</span><em><span style="font-weight: 400;">mobile</span></em><span style="font-weight: 400;">&nbsp;milik Kami.</span></p>
        <p><span style="font-weight: 400;">8.6.&nbsp;Semua Pengguna Terdaftar wajib mematuhi Syarat dan Ketentuan yang berlaku di Applikasi ini, dan tidak diperkenankan melakukan tindakan-tindakan seperti tertuang dalam poin 3.2, baik dalam keanggotaan Applikasi.</span></p>
        <ol start="9">
            <li><strong> UMUM</strong></li>
        </ol>
        <p><span style="font-weight: 400;">9.1. Penggunaan dan akses ke Situs ini diatur oleh Syarat dan Ketentuan serta Kebijakan Privasi Kami. Dengan mengakses atau menggunakan Applikasi ini, informasi, atau aplikasi lainnya dalam bentuk&nbsp;aplikasi&nbsp;</span><em><span style="font-weight: 400;">mobile</span></em><span style="font-weight: 400;">&nbsp;yang disediakan dalam Applikasi, berarti Anda telah memahami, menyetujui serta terikat dan tunduk dengan segala syarat dan ketentuan yang berlaku di Applikasi ini.</span></p>
        <p><span style="font-weight: 400;">9.2. Kami berhak untuk menutup atau mengubah atau memperbaharui Syarat dan Ketentuan ini setiap saat tanpa pemberitahuan, dan berhak untuk membuat keputusan akhir jika tidak ada ketidakcocokan. Kami tidak bertanggung jawab atas kerugian dalam bentuk apa pun yang timbul akibat perubahan pada Syarat dan Ketentuan.</span></p>
        <p><span style="font-weight: 400;">9.3.&nbsp;Jika Anda masih memerlukan jawaban atas pertanyaan yang tidak terdapat dalam Syarat dan Ketentuan ini, Anda dapat menghubungi Kami di email&nbsp;cs.relasibisnisbersama@gmail.com</span></p>
    </body>
</html>